apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/la-cc/gitops-robusta-argocd.git
    targetRevision: main
    path: ./helm/monitoring/robusta
    helm:
      releaseName: robusta
      valueFiles:
        - values.yaml
        - ./../../../cluster/in-cluster/monitoring/robusta/values.yaml
  destination:
    name: in-cluster
    namespace: robusta
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
