apiVersion: v1
data:
  url: aHR0cHM6Ly9naXRodWIuY29tL2xhLWNjL2dpdG9wcy1yb2J1c3RhLWFyZ29jZC5naXQ=
immutable: false
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: gitops-robusta-argocd-repo
  namespace: argocd
